# Welcome to MomScript! Follow the syntax examples below to get started!

print "Hello World!"

# declare a new variable, "x", an integer, and set its value to 17
set int x 17
print x

# change an existing variable's value!
change int x 20
print x

# get user input
input set username print "Enter your username: "
print username

# type casting
typechange username bool
print username

# print a variable's type
showtype x
